/* eslint-disable @typescript-eslint/no-explicit-any */
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";

const circularStd = localFont({
  src: "../../fonts/CircularStd.ttf",
  variable: "--font-circular-std",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`${circularStd.className} bg-black text-foreground`}>
        <NextIntlClientProvider messages={messages}>
          <header className="p-4 bg-background text-white h-[8vh] sticky top-0 "></header>
          <main>{children}</main>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
